### ISSUE TITLE
Doesn't feel complete

### ISSUE THREAD

**Issue by sebastian-zarzycki-apzumi** [cerbero90/laravel-dto#1]
There's no support for collections and even if mapped one by one, the resulting DTO created using fromModel, when serialized to JSON, still has properties with snake_case. 

I'm not sure how this is usable at this stage.

**Comment by cerbero90** [comment]
Hi @sebastian-zarzycki-es, it looks like you are indicating two issues here (correct me if I'm wrong):
1. lack of a helper to turn the items in a collection into DTOs
2. properties shown in snake case when a DTO is serialized to JSON

### Issue 1
The reason why there is no helper method for collections is that factory methods are meant to build a single instance of their own class. If we added a factory method for collections, we would need to support any class containing data that can be turned into DTO.

The solution that you also seem to have found is mapping the collection, which is the appropriate domain for this logic:
```php
$collection->map(fn ($model) => MyDto::fromModel($model));
```

### Issue 2
This is an expected behavior, arrays and JSONs follow the snake case format, whilst DTO properties follow the camel case format. If your needs are different from the standards, you may extend the DTO class to customize the related logic.

**Comment by sebastian-zarzycki-apzumi** [comment]
Thanks for the response. There are no such standards for JSON that you speak of. 

https://cryos.net/2018/04/json-camels-kebabs-and-snakes/
https://stackoverflow.com/questions/5543490/json-naming-convention

DTOs, other than choosing a set of data that should be transferred between server and client often serve the purpose of transforming the naming of such data (for various reasons, database/business logic naming can be sometimes different from external client api consuming logic). I guess I don't understand what is the purpose of library that magically transforms Eloquent model from snake_case to arbitrary camelCase, only to drop that in further transformations. I believe, for both cases one needs to have freedom in naming their DTO properties and in mapping them from and to external resources.

For now, if the assumption is that it considers DTO to be camelCased, it should at least be consistent everywhere and not revert to snake_case "just because". In an ideal world, this should be either a choice driven by a property (good) or a mapping table (from which source property to which DTO property and back) provided by user (better).

**Comment by cerbero90** [comment]
Not a problem, glad you raised this issue. For standards I meant the conventions followed by this package, poor wording.

> DTOs, other than choosing a set of data that should be transferred between server and client often serve the purpose of transforming the naming of such data

The Laravel package offers methods like `fromModel()` or `fromRequest()` to simplify the data mapping when keys coincide but we are not forced to instantiate DTOs by calling them. Custom mapping can be performed by manually instantiating a DTO object or calling the `make()` method:

```php
$dto = new MyDto(['favorite_color' => $request->color]);

$dto = MyDto::make(['favorite_color' => $request->color]);
```

> I guess I don't understand what is the purpose of library that magically transforms Eloquent model from snake_case to arbitrary camelCase, only to drop that in further transformations.

We are also not forced to name DTO properties in camel case, they can be named in snake case and preserve their format during the whole process.

> I believe, for both cases one needs to have freedom in naming their DTO properties and in mapping them from and to external resources.

Totally agree with you and this is indeed allowed by the package.

**Comment by sebastian-zarzycki-apzumi** [comment]
> The Laravel package offers methods like `fromModel()` or `fromRequest()` to simplify the data mapping when keys coincide but we are not forced to instantiate DTOs by calling them. 

Well yes, but then again, this can be also done completely "manually", without the need of this library. So what kind of gain it gives in this scenario?

> We are also not forced to name DTO properties in camel case, they can be named in snake case and preserve their format during the whole process.

I was under the impression that fromModel converts to camelCase. Not that I want to use snake_case, but are you saying, that there is a mean to control that? How?

> > I believe, for both cases one needs to have freedom in naming their DTO properties and in mapping them from and to external resources.
> 
> Totally agree with you and this is indeed allowed by the package.

Is it? Maybe I'm missing something then. So how do I achieve the initial scenario? Model in snake_case to DTO camelCase (with the possible option of changing the name of a property or two) and then send away as JSON, still camelCased?

**Comment by cerbero90** [comment]
> Well yes, but then again, this can be also done completely "manually", without the need of this library. So what kind of gain it gives in this scenario?

The package automates the generation of DTOs for models and related models, data mapping from requests, models and other sources as long as keys coincide and so on but it cannot automate every single scenario and yours sounds specific.

> I was under the impression that fromModel converts to camelCase. Not that I want to use snake_case, but are you saying, that there is a mean to control that? How?

The case of DTO properties is always respected, whether they are camel case or snake case. If your DTO has the property `full_name`, the property name won't be converted into `fullName` after mapping.

> So how do I achieve the initial scenario? Model in snake_case to DTO camelCase (with the possible option of changing the name of a property or two) and then send away as JSON, still camelCased?

Given the specificity of your scenario, I'd recommend to override the method `toArray()` in your DTO or in an abstract class if you want this behavior to be shared across all your DTOs.

**Comment by sebastian-zarzycki-apzumi** [comment]
> The case of DTO properties is always respected, whether they are camel case or snake case. If your DTO has the property `full_name`, the property name won't be converted into `fullName` after mapping.

I don't understand what you mean here. What mapping? Can you elaborate? Did you mean "source object" instead of DTO?

**Comment by cerbero90** [comment]
For mapping I mean the process where you map data from a request, model or other source into your DTO.

Imagine to have these properties in your DTO:
```php
/**
 * @property string $full_name
 * @property bool $isAdmin
 * @property Carbon $dateOfBirth
 */
```

And this array as data source:
```php
[
  'full_name' => 'John Doe',
  'is_admin' => true,
  'dateOfBirth' => '2000-01-01',
]
```

The case of DTO property names is always respected, as the package tries to match data source keys regardless their case:

```php
$dto->full_name; // string
$dto->isAdmin; // boolean
$dto->dateOfBirth; // Carbon instance
```

**Comment by sebastian-zarzycki-apzumi** [comment]
Here's a set of improvements I've made for myself. My DTOs extend this object. Perhaps you might want to incorporate some or all of it.

[DTO.php.zip](https://github.com/cerbero90/laravel-dto/files/5101069/DTO.php.zip)
