### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by elodieirdor** [cerbero90/laravel-dto#3]
Hey,

Thanks for this awesome package. I have tried to install it on a PHP 8 laravel app but I am having this issue :

Your requirements could not be resolved to an installable set of packages.

Problem 1
    - cerbero/dto 2.0.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - cerbero/laravel-dto 2.0.0 requires cerbero/dto ^2.0 -> satisfiable by cerbero/dto[2.0.0].
    - Root composer.json requires cerbero/laravel-dto ^2.0 -> satisfiable by cerbero/laravel-dto[2.0.0].

## Detailed description

Would you consider update the PHP requirements of cerbero/dto to PHP 8 ? I can make the PR if you want.

**Comment by cerbero90** [comment]
Hi @elodieirdor and thanks for using the package.

The DTO and Laravel DTO packages have just been updated, please make sure to require the version `2.1.0` of the Laravel package to ensure the compatibility with PHP 8.

The version `2.1.0` also introduces [global flags](https://github.com/cerbero90/laravel-dto#define-flags-globally), you may need to update your `dto.php` configuration file to use that feature.

Please let me know if you still have issues after the version bumping.

**Comment by elodieirdor** [comment]
Awesome 👍  Thanks!
